env:
  RUBY_VERSION: 3.1.2
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Maggie1641

name: Rails tests
on: [push, pull_request]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install PostgreSQL client
        run: sudo apt-get install -y libpq-dev

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U ${{ env.POSTGRES_USER }}; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install additional gems
        run: gem install brakeman rubocop

      - name: Create database
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Install Yarn
        run: npm install -g yarn

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      
      - name: Run tests with verbose output
        run: bundler exec rspec --format documentation

      - name: Run brakeman explicitly
        run: brakeman || echo "Brakeman failed"

      - name: Run rubocop explicitly
        run: bundler exec rubocop --force-exclusion vendor/*/** --out rubocop.txt || echo "Rubocop failed"

      - name: Ensure coverage exists before upload
        run: ls -la coverage || echo "No coverage found"

      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage

      - name: Upload Rubocop report
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: rubocop-report.txt
          path: rubocop.txt

      - name: Upload Brakeman report
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: brakeman-report.txt
          path: brakeman.txt